# Sponsorship
#
# GitHub will show a "Sponsor" button next to the repository.
# custom — for third-party platforms (Boosty, Patreon, Ko-fi, etc.).
# Comment out what you don't need.

github: [alexveliyar-coder]
custom:
  - https://boosty.to/veliyar_ensophia
